import Head from 'next/head'
function tnc() {
    return (
        <>
        <Head>
            <title>The Neuron Club | Terms & Conditions</title>
        </Head>
        <div className="policy max-w-4xl 2xl:max-w-5xl blur-white mx-auto p-10 my-10">
            <h4 className="text-3xl xl:text-4xl font-semibold text-white text-center"> Terms & Conditions </h4>
            <h1>
                1. Usage of The Neuron Club
            </h1>
            <ul>
                <li><p>The Neuron Club Platform (including any mobile based applications, website and web applications) is provided by The Neuron Club Media Technologies Pvt. Ltd. ("<b>The Neuron Club</b>"). Through The Neuron Club Platform any person (“<b>User</b>”) with a verified account can access and participate in the services provided via The Neuron Club Platform. Through The Neuron Club Platform a User, exercising knowledge about a given subject and based on publicly available information (including such information collated and made available through The Neuron Club Platform) can bid on the probability of the occurrence of a specified event.</p></li>
                <li><p>A User accessing The Neuron Club The Neuron Club Platform shall be bound by these Terms and Conditions, and all other rules, regulations and terms of use referred to herein or provided by The Neuron Club in relation to any services provided via The Neuron Club Platform (“The Neuron Club Services”).</p></li>
                <li><p>The Neuron Club shall be entitled to modify these Terms and Conditions, rules, regulations and terms of use referred to herein or provided by The Neuron Club in relation to any The Neuron Club Services, at any time, by posting the same on The Neuron Club. Use of The Neuron Club constitutes the User's acceptance of such Terms and Conditions, rules, regulations and terms of use referred to herein or provided by The Neuron Club in relation to any The Neuron Club Services, as may be amended from time to time. The Neuron Club may, at its sole discretion, also notify the User of any change or modification in these Terms and Conditions, rules, regulations and terms of use referred to herein or provided by The Neuron Club, by way of sending an email to the User's registered email address or posting notifications in the User accounts. The User may then exercise the options provided in such an email or notification to indicate non-acceptance of the modified Terms and Conditions, rules, regulations and terms of use referred to herein or provided by The Neuron Club. If such options are not exercised by the User within the time frame prescribed in the email or notification, the User will be deemed to have accepted the modified Terms and Conditions, rules, regulations and terms of use referred to herein or provided by The Neuron Club.</p></li>
                <li><p>Certain The Neuron Club Services being provided on The Neuron Club may be subject to additional rules and regulations set down in that respect. To the extent that these Terms and Conditions are inconsistent with the additional conditions set down, the additional conditions shall prevail.</p></li>
                <li><p>The Neuron Club may, at its sole and absolute discretion:</p></li>
                <ul>
                    <li><p>Restrict, suspend, or terminate any User's access to all or any part of The Neuron Club or The Neuron Club Platform Services</p></li>
                    <li><p>Change, suspend, or discontinue all or any part of The Neuron Club Platform Services</p></li>
                    <li><p>Reject, move, or remove any material that may be submitted by a User</p></li>
                    <li><p>Move or remove any content that is available on The Neuron Club Platform</p></li>
                    <li><p>Deactivate or delete a User's account and all related information and files on the account</p></li>
                    <li><p>Establish general practices and limits concerning use of The Neuron Club Platform</p></li>
                    <li><p>Offer discounts or cash rewards to its users in a form it deems fit ("<b>Cash Bonus</b>")</p></li>
                    <li><p>Revise or make additions and/or deletions to the roster of questions, data, information provided in relation to a particular outcome that is being bid on</p></li>
                    <li><p>Assign its rights and liabilities to all User accounts hereunder to any entity (post such assignment intimation of such assignment shall be sent to all Users to their registered email ids)</p></li>
                </ul>
                <li><p>In the event any User breaches, or The Neuron Club reasonably believes that such User has breached these Terms and Conditions, or has illegally or improperly used The Neuron Club or The Neuron Club Services, The Neuron Club may, at its sole and absolute discretion, and without any notice to the User, restrict, suspend or terminate such User's access to all or any part of The Neuron Club Platform, deactivate or delete the User's account and all related information on the account, delete any content posted by the User on The Neuron Club and further, take technical and legal steps as it deems necessary.</p></li>
                <li><p>If The Neuron Club charges its Users a platform fee in respect of any The Neuron Club Services, The Neuron Club shall, without delay, repay such platform fee in the event of suspension or removal of the User's account or The Neuron Club Services on account of any negligence or deficiency on the part of The Neuron Club, but not if such suspension or removal is affected due to:</p></li>
                <ul>
                    <li><p>any breach or inadequate performance by the User of any of these Terms and Conditions or</p></li>
                    <li><p>any circumstances beyond the reasonable control of The Neuron Club</p></li>
                </ul>
                <li><p>By accepting these Terms and Conditions Users are providing their consent to receiving communications such as announcements, administrative messages and advertisements from The Neuron Club or any of its partners, licensors or associates.
                </p></li>
            </ul>

            <h1>
                2. Participation
            </h1>
            <ul>
                <li><p>As part of its services The Neuron Club shall, via The Neuron Club Platform, make available questions relating to the probability of the occurrence of a specified future event, data and information collated from publicly available sources related to the specified future event, and/or the ability for Users to add their own opinions, data/information related to a particular future event.</p></li>
                <li><p>Depending upon the potential outcome for each specified future event, the time period of occurrence of such specified future event, the number of bids received for a specified future event and any other factors that might be relevant in The Neuron Club’s sole discretion, Users may be allowed to edit their bids and/or place multiple bids on the occurrence of a specified future event.</p></li>
                <li><p>The Neuron Club reserves the right to abandon a specific question or set of questions related to a specified future event, or adjust the deadline for bidding on such specified future event in certain specific, uncertain scenarios, which are beyond The Neuron Club’s reasonable control. The Neuron Club shall endeavor to send communications through various modes including but not limited to emails, about any such change to keep the User updated.</p></li>
                <li><p>Bidding on certain specified future events might have specific rules that The Neuron Club will notify the User(s) before making the bid. Such rules will be in addition to these Terms and Conditions unless otherwise specified in the said rules.</p></li>
                <li><p>To place a bid a User must pay a certain amount that is equivalent/commensurate with the likelihood of occurrence of a specified future event. A winning bid is determined based on the occurrence and outcome of a specified future event. A User’s bid on the said event will be deemed to be successful if the parameters which formed the basis for the User making a bid are met and/or have occurred. If the parameters which formed the basis for the User making a bid are not met and/or have not occurred the bid shall not be successful.</p></li>
                <li><p>All Users understand and acknowledge that participation via The Neuron Club Platform and placing bids on specified future events by a User is based on Users’ individual analysis of the possibility of occurrence of a specified future event. While The Neuron Club collates and provides data and information related to the future events from publicly available sources on The Neuron Club Platform, Users are encouraged to use their own methods to collect/gather/collate and analyze information related to the specified future event and bid on the said event only after making a thorough and detailed analysis and determination as to the possibility of success of their individual bids</p></li>
                <li><p>To bid on a specified future event a User must add money to their account on The Neuron Club Platform (“<b>The Neuron Club Account</b>”). The Neuron Club may, in its sole discretion, specify the amounts that can be added and/or held by a User either in aggregate or in tranches. Credits and debits towards making bids, winning bids or losing bids will be made to and from (as the case may be) the User’s The Neuron Club Account.</p></li>
            </ul>

            <h1>
                3. Intellectual Property
            </h1>
            <ul>
                <li><p>The Neuron Club includes a combination of content collected/collated/analysed by The Neuron Club, its partners, affiliates, licensors, associates and/or Users. The intellectual property rights ("<b>Intellectual Property Rights</b>") in all software underlying The Neuron Club and The Neuron Club Platform and material published on The Neuron Club Platform, including (but not limited to) software, advertisements, content (whether written, audio and/or visual), photographs, graphics, images, illustrations, graphs, charts, marks, logos, audio or video clippings, animations etc. is owned by The Neuron Club, its partners, licensors and/or associates. Users may not modify, publish, transmit, participate in the transfer or sale of, reproduce, create derivative works of, distribute, publicly perform, publicly display, or in any way exploit any of the materials or content on The Neuron Club either in whole or in part without express written license from The Neuron Club</p></li>
                <li><p>Users are solely responsible for all materials (whether publicly posted or privately transmitted) that they upload, post, e-mail, transmit, or otherwise make available via The Neuron Club Platform ("<b>Users' Content</b>"). Each User represents and warrants that they own all Intellectual Property Rights in the Users’ Content and that no part of the User's Content infringes any third party rights. Users further confirm and undertake to not display or use of the names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights of any third party on The Neuron Club Platform. Users agree to indemnify and hold harmless The Neuron Club, its directors, employees, affiliates and assigns against all costs, damages, loss and harm including towards litigation costs and counsel fees, in respect of any third party claims that may be initiated including for infringement of Intellectual Property Rights arising out of such display or use of the names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on The Neuron Club Platform, by such User or through the User's commissions or omissions</p></li>
                <li><p>Users hereby grant to The Neuron Club and its affiliates, partners, licensors and associates a worldwide, irrevocable, royalty-free, non-exclusive, sub-licensable license to use, reproduce, create derivative works of, distribute, publicly perform, publicly display, transfer, transmit, and/or publish Users' Content for any of the following purposes:</p></li>
                <ul>
                    <li><p>displaying Users' Content on The Neuron Club</p></li>
                    <li><p>distributing Users' Content, either electronically or via other media, to other Users seeking to download or otherwise acquire it, and/or</p></li>
                    <li><p>This license shall apply to the distribution and the storage of Users' Content in any form, medium, or technology</p></li>
                    <li><p>All names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on The Neuron Club Platform belonging to any person (including a User), entity or third party are recognized as proprietary to the respective owners and any claims, controversy or issues against these names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights must be directly addressed to the respective parties under notice to The Neuron Club.</p></li>
                </ul>
            </ul>

            <h1>4. Third Party Sites, Services and Products</h1>
            <ul>
                <li><p>Links to other Internet sites owned and operated by third parties may be provided via The Neuron Club Platform. Users' use of each of those sites is subject to the conditions, if any, posted by the sites. The Neuron Club does not exercise control over any Internet sites apart from The Neuron Club Platform and cannot be held responsible for any content residing in any third-party Internet site. The Neuron Club's inclusion of third-party content or links to third-party Internet sites is not an endorsement by The Neuron Club of such third-party Internet sites.</p></li>
                <li><p>Users' correspondence, transactions/offers or related activities with third parties, including payment providers and verification service providers, are solely between the User and that third party. Users' correspondence, transactions and usage of the services/offers of such third party shall be subject to the terms and conditions, policies and other service terms adopted/implemented by such third party, and the User shall be solely responsible for reviewing the same prior to transacting or availing of the services/offers of such third party. The User agrees that The Neuron Club will not be responsible or liable for any loss or damage of any sort incurred as a result of any such transactions/offers with third parties. Any questions, complaints, or claims related to any third party product or service should be directed to the appropriate vendor.</p></li>
                <li><p>The Neuron Club Platform contains content that is created by The Neuron Club as well as content provided by third parties. The Neuron Club does not guarantee the accuracy, integrity, quality of the content provided by third parties and such content may not be relied upon by the Users in utilizing The Neuron Club Services provided on The Neuron Club Platform</p></li>
            </ul>

            <h1>5. Privacy Policy</h1>
            <ul>
                <li><p>All information collected from Users, such as registration and credit card information, is subject to The Neuron Club's Privacy Policy which is available at Privacy Policy</p></li>
            </ul>

            <h1>6. User Conduct</h1>
            <ul>
                <li><p>Users agree to abide by these Terms and Conditions and all other rules, regulations and terms of use of the Website. In the event User does not abide by these Terms and Conditions and all other rules, regulations and terms of use, The Neuron Club may, at its sole and absolute discretion, take necessary remedial action, including but not limited to:</p></li>
                <ul>
                    <li><p>restricting, suspending, or terminating any User's access to all or any part of The Neuron Club Services</p></li>
                    <li><p>deactivating or deleting a User's account and all related information and files on the account. Any amount remaining unused in the User's The Neuron Club Account on the date of deactivation or deletion shall be transferred to the User's bank account on record with The Neuron Club subject to a processing fee (if any) applicable on such transfers as set out herein</p></li>
                </ul>
                <li><p>Users agree to provide true, accurate, current and complete information at the time of registration and at all other times (as required by The Neuron Club). Users further agree to update and keep updated their registration information</p></li>
                <li><p>A User shall not register or operate more than one User account with The Neuron Club.</p></li>
                <li><p>Users agree to ensure that they can receive all communication from The Neuron Club by marking emails or sending SMSs from The Neuron Club. The Neuron Club shall not be held liable if any e-mail/SMS remains unread by a User as a result of such e-mail getting delivered to the User's junk or spam folder.</p></li>
                <li><p>Any password issued by The Neuron Club to a User may not be revealed to anyone else. Users may not use anyone else's password. Users are responsible for maintaining the confidentiality of their accounts and passwords. Users agree to immediately notify The Neuron Club of any unauthorized use of their passwords or accounts or any other breach of security</p></li>
                <li><p>Users agree to exit/log-out of their accounts at the end of each session. The Neuron Club shall not be responsible for any loss or damage that may result if the User fails to comply with these requirements.</p></li>
                <li><p>Users agree not to use cheats, exploits, automation, software, bots, hacks or any unauthorized third party software designed to modify or interfere with The Neuron Club Services and/or The Neuron Club experience or assist in such activity</p></li>
                <li><p>Users agree not to copy, modify, rent, lease, loan, sell, assign, distribute, reverse engineer, grant a security interest in, or otherwise transfer any right to the technology or software underlying The Neuron Club or The Neuron Club’s Services.</p></li>
                <li><p>Users agree not to disrupt, overburden, or aid or assist in the disruption or overburdening of (a) any computer or server used to offer or support The Neuron Club or The Neuron Club’s Services (each a "Server"); or (2) the enjoyment of The Neuron Club Services by any other User or person</p></li>
                <li><p>Users agree not to institute, assist or become involved in any type of attack, including without limitation to distribution of a virus, denial of service, or other attempts to disrupt The Neuron Club Services or any other person's use or enjoyment of The Neuron Club Services.</p></li>
                <li><p>Users shall not attempt to gain unauthorized access to the User accounts, Servers or networks connected to The Neuron Club Services by any means other than the User interface provided by The Neuron Club, including but not limited to, by circumventing or modifying, attempting to circumvent or modify, or encouraging or assisting any other person to circumvent or modify, any security, technology, device, or software that underlies or is part of The Neuron Club Services.</p></li>
                <li><p>Users shall not publish any content that is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any person.</p></li>
                <li><p>Without limiting the foregoing, Users agree not to use The Neuron Club for any of the following:</p></li>
                <ul>
                    <li><p>To engage in any obscene, offensive, indecent, racial, communal, anti-national, objectionable, defamatory or abusive action or communication</p></li>
                    <li><p>To harass, stalk, threaten, or otherwise violate any legal rights of other individuals</p></li>
                    <li><p>To publish, post, upload, e-mail, distribute, or disseminate (collectively, "<b>Transmit</b>") any inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful content</p></li>
                    <li><p>To Transmit files that contain viruses, corrupted files, or any other similar software or programs that may damage or adversely affect the operation of another person's computer, The Neuron Club, any software, hardware, or telecommunications equipment</p></li>
                    <li><p>To advertise, offer or sell any goods or services for any commercial purpose on The Neuron Club without the express written consent of The Neuron Club</p></li>
                    <li><p>To download any file, recompile or disassemble or otherwise affect our products that you know or reasonably should know cannot be legally obtained in such manner</p></li>
                    <li><p>To falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or the source of software or other material</p></li>
                    <li><p>To restrict or inhibit any other user from using and enjoying any public area within our sites</p></li>
                    <li><p>To collect or store personal information about other Users</p></li>
                    <li><p>To interfere with or disrupt The Neuron Club and/or The Neuron Club Platform, The Neuron Club servers, or The Neuron Club networks</p></li>
                    <li><p>To impersonate any person or entity, including, but not limited to, a representative of The Neuron Club, or falsely state or otherwise misrepresent User's affiliation with a person or entity</p></li>
                    <li><p>To forge headers or manipulate identifiers or other data in order to disguise the origin of any content transmitted through The Neuron Club or to manipulate User's presence on The Neuron Club(s)</p></li>
                    <li><p>To take any action that imposes an unreasonably or disproportionately large load on The Neuron Club’s infrastructure</p></li>
                    <li><p>To engage in any illegal activities.</p></li>
                    <li><p>To engage in any action that threatens the unity, integrity, defence, security or sovereignty of any country, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting other nations</p></li>
                </ul>
                <li><p>If a User chooses a username that, in The Neuron Club's considered opinion is obscene, indecent, abusive or that might subject The Neuron Club to public disparagement or scorn, or a name which is an official team/league/franchise names and/or name of any sporting personality, as the case may be, The Neuron Club reserves the right, without prior notice to the User, to restrict usage of such names, which in The Neuron Club’s opinion fall within any of the said categories and/or change such username and intimate the User or delete such username and posts from The Neuron Club, deny such User access to The Neuron Club, or any combination of these options.</p></li>
                <li><p>Unauthorized access to The Neuron Club Platform is a breach of these Terms and Conditions, and a violation of the law. Users agree not to access The Neuron Club Platform by any means other than through the interface that is provided by The Neuron Club via The Neuron Club Platform for use in accessing The Neuron Club Platform. Users agree not to use any automated means, including, without limitation, agents, robots, scripts, or spiders, to access, monitor, or copy any part of our sites, except those automated means that we have approved in advance and in writing.</p></li>
                <li><p>Use of The Neuron Club Platform is subject to existing laws and legal processes. Nothing contained in these Terms and Conditions shall limit The Neuron Club's right to comply with governmental, court, and law-enforcement requests or requirements relating to Users' use of The Neuron Club</p></li>
                <li><p>Persons below the age of eighteen (18) years are not allowed to register with or place bids via The Neuron Club Platform. All persons interested in becoming The Neuron Club Users must disclose their age at the time of getting access to The Neuron Club Platform. If a person declares a false age, The Neuron Club shall not be held responsible and such person shall, in addition to forfeiting any and all rights over their The Neuron Club Account, shall indemnify and hold The Neuron Club, its Directors, officers, employees, agents, affiliates harmless of any and all losses that may be suffered by The Neuron Club its Directors, officers, employees, agents, affiliates by virtue of such false declaration being made. In case the person making the false declaration is below the age of 18 such person’s legal guardians shall indemnify and hold The Neuron Club, its Directors, officers, employees, agents, affiliates harmless of any and all losses that may be suffered by The Neuron Club its Directors, officers, employees, agents, affiliates by virtue of such false declaration having been made by said person</p></li>
                <li><p>The Neuron Club may not be held responsible for any content contributed by Users on The Neuron Club Platform</p></li>
            </ul>
            <h1>7. Eligibility</h1>
            <ul>
                <li><p>The Neuron Club Platform is open only to persons above the age of 18 years.</p></li>
                <li><p>Persons who wish to participate must have a valid email address.</p></li>
                <li><p>The Neuron Club may on receipt of information bar a person from participation and/or withdrawing amounts from their The Neuron Club Account if such person is found to be one with insider knowledge of certain specified future events on which such person is/has placed a bid</p></li>
                <li><p>Only those Participants who have successfully registered on The Neuron Club Platform shall be eligible to bid on the outcome of specified future events.</p></li>
            </ul>

            <h1>8. Payment Terms</h1>
            <ul>
                <li><p>In respect of any bids placed via The Neuron Club Platform Users agree to be bound by the following payment terms:</p></li>
                <ul>
                    <li><p>A User can only place a bid if the User’s The Neuron Club Account has a minimum balance that corresponds to the amount the User wishes to bid.</p></li>
                    <li><p>When a User places a bid The Neuron Club shall place a hold on the bid amount in the User’s account.</p></li>
                    <li><p>The Neuron Club reserves the right to charge a Platform Fee, which would be specified and notified by The Neuron Club from time to time. The Platform Fee (inclusive of applicable tax thereon) will be debited from a User’s account balance at the time of determination of the outcome of a specified future event on which the user has placed a bid.</p></li>
                    <li><p>All bid amounts shall be debited from the User’s The Neuron Club Account and all winning bids shall be credited to the User’s The Neuron Club Account after deduction of the Platform Fee.</p></li>
                    <li><p>If a User has not made any bids for a continuous period of 365 days, all amounts in the said User’s The Neuron Club Account shall be forfeited. The Neuron Club, in its sole discretion, may choose to reverse such forfeiture, either in whole or part.</p></li>
                    <li><p>The Neuron Club, may at its sole discretion, fix limits on the amount a user may be allowed to deposit into or withdraw from their The Neuron Club Account and define minimum limits which must be met in a User’s Account before allowing a withdrawal. When a User is eligible to withdraw money from their User Account, The Neuron Club shall effect an online transfer to the User's bank account on record with The Neuron Club within a commercially reasonable period of time. Such transfer will reflect as a debit to the User's The Neuron Club Account. The Neuron Club shall not charge any processing fee for the online transfer of such amount from The Neuron Club Account to the User's bank account on record with The Neuron Club. Users may be required to provide certain “Know Your Customer” (“<b>KYC</b>”) documents in order for The Neuron Club to process the withdrawal request. The name mentioned on the User's KYC document(s) should correspond with the name provided by the User at the time of registration on The Neuron Club, as well as the name and address existing in the records of the User's bank account as provided to The Neuron Club. In the event that no bank account has been registered by the User against such User's account with The Neuron Club, or the User has not verified his/her User account with The Neuron Club, to The Neuron Club's satisfaction and in accordance with these Terms and Conditions, and in case the User fails to register a bank account with his/her User Account and/or to verify his/her User Account, The Neuron Club shall not transfer any amounts to the User.</p></li>
                    <li><p>Further, in order to conduct promotional activities, The Neuron Club may, from time to time, gratuitously issue certain amounts (“<b>Promotional Balance</b>”) to the User for the purpose of participation on The Neuron Club Platform. The usage of any Promotional Balance issued by The Neuron Club to the User shall be subject to the limitations and restrictions as determined by The Neuron Club in its sole discretion. The issue of any Promotional Balance to a User is subject to the sole discretion of The Neuron Club and cannot be demanded by any User as a matter of right</p></li>
                    <li><p>Subject to these Terms and Conditions and any additional Terms published by The Neuron Club from time to time, Users agree that once they confirm a transaction on The Neuron Club, they shall be bound by and make payment for that transaction</p></li>
                </ul>
            </ul>

            <h1>9. Dispute and Dispute Resolution</h1>
            <ul>
                <li><p>If any dispute arising out of, or in connection with, The Neuron Club Services provided by The Neuron Club via The Neuron Club Platform, the construction, validity, interpretation and enforceability of these Terms and Conditions, or the rights and obligations of the User(s) or The Neuron Club, as well as the exclusive jurisdiction to grant interim or preliminary relief in case of any dispute referred to arbitration as given below arises between the User(s) and The Neuron Club (“<b>Dispute</b>”), the disputing parties hereto shall endeavor to settle such Dispute amicably. The attempt to bring about an amicable settlement shall be considered to have failed if not resolved within 30 (thirty) days from the date of communicating the Dispute in writing.</p></li>
                <li><p>If the parties are unable to amicably settle the Dispute as mentioned above, any party to the Dispute shall be entitled to serve a notice invoking Arbitration. The Dispute shall be referred to and finally resolved by arbitration. The Arbitration shall be conducted by an Arbitral Tribunal consisting of a sole arbitrator in accordance with the Rules of the Delhi International Arbitration Centre (“<b>DIAC Rules</b>”), which rules are deemed to be incorporated by reference in this clause. The seat of the arbitration shall be New Delhi. The Tribunal shall consist of one arbitrator. The language of the arbitration shall be English. The law governing the arbitration agreement shall be Indian Law.</p></li>
                <li><p>Nothing shall preclude any Party from seeking interim or permanent equitable or injunctive relief, or both, from the competent courts at New Delhi, having jurisdiction to grant relief on any Disputes. The pursuit of equitable or injunctive relief shall not be a waiver of the duty of the Parties to pursue any remedy (including for monetary damages) through the arbitration described herein.</p></li>
                <li><p>The arbitration award will be final and binding on the Parties.</p></li>
            </ul>

            <h1>10. Release and Limitations of Liability</h1>
            <ul>
                <li><p>Users shall access The Neuron Club Services provided via The Neuron Club Platform voluntarily and at their own risk. The Neuron Club shall, under no circumstances be held responsible or liable on account of any loss or damage sustained by Users or any other person or entity during the course of access to The Neuron Club Platform.</p></li>
                <li><p>By accessing The Neuron Club Platform and The Neuron Club Services provided therein, Users hereby release from and agree to indemnify The Neuron Club, and/or any of its directors, employees, partners, associates and licensors, from and against all liability, cost, loss or expense arising out their access of The Neuron Club Platform and The Neuron Club Services including (but not limited to) personal injury and damage to property and whether direct, indirect, consequential, foreseeable, due to some negligent act or omission on their part, or otherwise.</p></li>
                <li><p>The Neuron Club accepts no liability, whether jointly or severally, for any errors or omissions, whether on behalf of itself or third parties in relation to the data/information collated and published on The Neuron Club Platform.</p></li>
                <li><p>Users shall be solely responsible for any consequences which may arise due to their access to The Neuron Club Services by conducting an illegal act or due to non-conformity with these Terms and Conditions and other rules and regulations in relation to The Neuron Club Services, including provision of incorrect personal details. Users also undertake to indemnify The Neuron Club and their respective officers, directors, employees and agents on the happening of such an event (including without limitation cost of attorney, legal charges etc.) on full indemnity basis for any loss/damage suffered by The Neuron Club on account of such act on the part of the Users.</p></li>
                <li><p>Users shall indemnify, defend, and hold The Neuron Club harmless from any third party/entity/organization claims arising from or related to such User's engagement with The Neuron Club Platform. In no event shall The Neuron Club be liable to any User for acts or omissions arising out of or related to User's engagement with The Neuron Club Platform</p></li>
                <li><p>In consideration of The Neuron Club allowing Users to access The Neuron Club Platform, to the maximum extent permitted by law, the Users waive and release each and every right or claim, all actions, causes of actions (present or future) each of them has or may have against The Neuron Club, its respective agents, directors, officers, business associates, group companies, sponsors, employees, or representatives for all and any injuries, accidents, or mishaps (whether known or unknown) or (whether anticipated or unanticipated) arising out of the provision of The Neuron Club Services.</p></li>
            </ul>

            <h1>11. Disclaimers</h1>
            <ul>
                <li><p>To the extent permitted under law, neither The Neuron Club nor its parent/holding company, subsidiaries, affiliates, directors, officers, professional advisors, employees shall be responsible for the deletion, the failure to store, the mis-delivery, or the untimely delivery of any information or material.</p></li>
                <li><p>To the extent permitted under law, The Neuron Club shall not be responsible for any harm resulting from downloading or accessing any information or material, the quality of servers, products, The Neuron Club Services or sites.</p></li>
                <li><p>Any material accessed, downloaded or otherwise obtained through The Neuron Club Platform is done at the User's discretion, competence, acceptance and risk, and the User will be solely responsible for any potential damage to User's computer system or loss of data that results from a User's download of any such material.</p></li>
                <li><p>The Neuron Club shall make best endeavours to ensure that The Neuron Club(s) is error-free and secure, however, neither The Neuron Club nor any of its partners, licensors or associates makes any warranty that:</p></li>
                <ul>
                    <li><p>The Neuron Club Platform will meet Users' requirements</p></li>
                    <li><p>The Neuron Club Platform will be uninterrupted, timely, secure, or error free</p></li>
                    <li><p>the results that may be obtained from the use of The Neuron Club Platform will be accurate or reliable and</p></li>
                    <li><p>the quality of any products, The Neuron Club Services, information, or other material that Users purchase or obtain through The Neuron Club Platform will meet Users' expectations</p></li>
                </ul>
                <li><p>In case The Neuron Club discovers any error, The Neuron Club reserves the right (exercisable at its discretion) to rectify the error in such manner as it deems fit, including through a set-off of the erroneous payment from amounts due to the User or deduction from the User's account of the amount of erroneous payment. In case of exercise of remedies in accordance with this clause, The Neuron Club agrees to notify the User of the error and of the exercise of the remedy(ies) to rectify the same.</p></li>
                <li><p>To the extent permitted under law, neither The Neuron Club nor its partners, licensors or associates shall be liable for any direct, indirect, incidental, special, or consequential damages arising out of the use of or inability to use our sites, even if we have been advised of the possibility of such damages.</p></li>
                <li><p>Any The Neuron Club Services being hosted or provided, or intended to be hosted on The Neuron Club platform and requiring specific permission or authority from any statutory authority or any state or the central government, or the board of directors shall be deemed cancelled or terminated, if such permission or authority is either not obtained or denied either before or after the availability of the relevant The Neuron Club Services are hosted or provided.</p></li>
                <li><p>To the extent permitted under law, in the event of suspension or closure of any The Neuron Club Services Users shall not be entitled to make any demands, claims, on any nature whatsoever.</p></li>
            </ul>

            <h1>12. Grievance Redressal Mechanism</h1>
            <ul>
                <li><p>In case a User has any complaints or grievance pertaining to (i) any Content that a User believes violates these Terms (other than an infringement of Intellectual Property Rights), (ii) Users’ access to The Neuron Club Platform or (iii) any Content which a User believes is, prima facie, in the nature of any material which is obscene, defamatory towards the complainant or any person on whose behalf such User is making the complaint, or is in the nature of impersonation in an electronic form, including artificially morphed images of such individual, please share the same with us by writing to: <b>contact@TheNeuron.Club</b></p></li>
                <li><p>In the complaint or grievance, the User shall include the following information:</p></li>
                <ul>
                    <li><p>Name and contact details: name, address, contact number and email address</p></li>
                    <li><p>Relation to the subject matter of the complaint, i.e. complainant or person acting on behalf of an affected person</p></li>
                    <li><p>The name and age of the person aggrieved or affected by the subject matter of the complaint, in case the User is acting on behalf of such person and a statement that the User is authorised to act on behalf of such person and to provide such person's personal information to The Neuron Club in relation to the complaint/grievance</p></li>
                    <li><p>Description of the complaint or grievance with clear identification of the Content in relation to which such complaint or grievance is made</p></li>
                    <li><p>A statement that the User believes, in good faith, that the Content violates these Terms and Conditions</p></li>
                    <li><p>A statement that the information provided in the complaint or grievance is accurate.</p></li>
                </ul>
                <li><p>The Neuron Club respects the Intellectual Property Rights of others. All names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on The Neuron Club Platform belonging to any person (including User), entity or third party are recognized as proprietary to the respective owners. Users are requested to send The Neuron Club a written notice/ intimation if Users notice any act of infringement on The Neuron Club Platform, which must include the following information:</p></li>
                <ul>
                    <li><p>A clear identification of the copyrighted work allegedly infringed;</p></li>
                    <li><p>A clear identification of the allegedly infringing material on The Neuron Club Platform;</p></li>
                    <li><p>Contact details: name, address, e-mail address and phone number;</p></li>
                    <li><p>A statement that the User believes, in good faith, that the use of the copyrighted material allegedly infringed on The Neuron Club Platform is not authorized by the User’s agent or the law;</p></li>
                    <li><p>A statement that the information provided in the notice is accurate and that the signatory is authorized to act on behalf of the owner of an exclusive copyright right that is allegedly infringed;</p></li>
                    <li><p>User’s signature or a signature of the User’s authorized agent.</p></li>
                </ul>
            </ul>
            <p>The aforesaid notices can be sent to the Company by email at contact@TheNeuron.Club </p>
            <p>On receiving such complaint, grievance or notice, The Neuron Club reserves the right to investigate and/or take such action as The Neuron Club may deem appropriate. The Neuron Club may reach out to the User to seek further clarification or assistance with the investigation, or verify the statements made in the complaint, grievance or notice, and the User acknowledges that timely assistance with the investigation would facilitate the redressal of the same</p>
        </div>
        </>
    )
}

export default tnc
